<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2826" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:21Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="2826" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:21Z">
      <class name="com.sudhir.APIRestTestNG.testcases.TestCustomerAPI">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeSuite" is-config="true" duration-ms="627" started-at="2021-01-24T22:10:18Z" finished-at="2021-01-24T22:10:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeClass" is-config="true" duration-ms="3" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="m" duration-ms="9" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m(TestCustomerAPI.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m -->
        <test-method status="SKIP" signature="m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="m" duration-ms="1" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m(TestCustomerAPI.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m status=SKIP method=TestCustomerAPI.m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m status=SKIP method=TestCustomerAPI.m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="m" duration-ms="2" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m(TestCustomerAPI.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m status=SKIP method=TestCustomerAPI.m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="m" duration-ms="1" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m(TestCustomerAPI.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=m status=FAILURE method=TestCustomerAPI.m()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.m()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidData(java.util.Hashtable)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="validateCreateCustomerAPIWithValidData" duration-ms="2411" started-at="2021-01-24T22:10:19Z" data-provider="dp2" finished-at="2021-01-24T22:10:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expectedEmailId=apiTrainer111@way2automation.com, expectedStatusCode=200, arguments=email:apiTrainer111@way2automation.com;description:This is your api automation trainer;balance:100000, endpoint=/customers}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidData -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:19Z" finished-at="2021-01-24T22:10:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.validateCreateCustomerAPIWithValidData(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:21Z" finished-at="2021-01-24T22:10:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateCreateCustomerAPIWithValidData status=SUCCESS method=TestCustomerAPI.validateCreateCustomerAPIWithValidData(java.util.Hashtable)[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.sudhir.APIRestTestNG.testcases.TestCustomerAPI.validateCreateCustomerAPIWithValidData(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.sudhir.APIRestTestNG.testcases.TestCustomerAPI@3c407114]" name="afterSuite" is-config="true" duration-ms="0" started-at="2021-01-24T22:10:21Z" finished-at="2021-01-24T22:10:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.sudhir.APIRestTestNG.testcases.TestCustomerAPI -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
